# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/galaxys2plus-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/galaxys2plus-common/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/galaxys2plus-common/proprietary/bin/BCM4330B1_002.001.003.0876.0996.hcd:system/bin/BCM4330B1_002.001.003.0876.0996.hcd \
    vendor/samsung/galaxys2plus-common/proprietary/bin/bkmgrd:system/bin/bkmgrd \
    vendor/samsung/galaxys2plus-common/proprietary/bin/cate_rpc_util:system/bin/cate_rpc_util \
    vendor/samsung/galaxys2plus-common/proprietary/bin/emma:system/bin/emma \
    vendor/samsung/galaxys2plus-common/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/galaxys2plus-common/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/galaxys2plus-common/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/galaxys2plus-common/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/samsung/galaxys2plus-common/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/galaxys2plus-common/proprietary/bin/mttlogger:system/bin/mttlogger \
    vendor/samsung/galaxys2plus-common/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/galaxys2plus-common/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/galaxys2plus-common/proprietary/bin/tvserver:system/bin/tvserver \
    vendor/samsung/galaxys2plus-common/proprietary/bin/vcdbg:system/bin/vcdbg \
    vendor/samsung/galaxys2plus-common/proprietary/bin/vclmk:system/bin/vclmk \
    vendor/samsung/galaxys2plus-common/proprietary/bin/vcos-version:system/bin/vcos-version \
    vendor/samsung/galaxys2plus-common/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/galaxys2plus-common/proprietary/etc/camera_info.ini:system/etc/camera_info.ini \
    vendor/samsung/galaxys2plus-common/proprietary/etc/DiamondVoice_Filter_NB.txt:system/etc/DiamondVoice_Filter_NB.txt \
    vendor/samsung/galaxys2plus-common/proprietary/etc/DiamondVoice_Filter_WB.txt:system/etc/DiamondVoice_Filter_WB.txt \
    vendor/samsung/galaxys2plus-common/proprietary/etc/DiamondVoice_NB.txt:system/etc/DiamondVoice_NB.txt \
    vendor/samsung/galaxys2plus-common/proprietary/etc/DiamondVoice_WB.txt:system/etc/DiamondVoice_WB.txt \
    vendor/samsung/galaxys2plus-common/proprietary/etc/gps/glconfig.xml:system/etc/gps/glconfig.xml \
    vendor/samsung/galaxys2plus-common/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/galaxys2plus-common/proprietary/etc/sensors.conf:system/etc/sensors.conf \
    vendor/samsung/galaxys2plus-common/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/galaxys2plus-common/proprietary/etc/Volume.db:system/etc/Volume.db \
    vendor/samsung/galaxys2plus-common/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/galaxys2plus-common/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/galaxys2plus-common/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/galaxys2plus-common/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/galaxys2plus-common/proprietary/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/hw/audio.hdmi.capri.so:system/lib/hw/audio.hdmi.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/hw/audio.primary.capri.so:system/lib/hw/audio.primary.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/hw/audio.usb.capri.so:system/lib/hw/audio.usb.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/hw/gps.capri.so:system/lib/hw/gps.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/hw/sensors.capri.so:system/lib/hw/sensors.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/lib_SamsungRec_V01006.so:system/lib/lib_SamsungRec_V01006.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/lib_SoundAlive_V01013n.so:system/lib/lib_SoundAlive_V01013n.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libat.so:system/lib/libat.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libat_stubs.so:system/lib/libat_stubs.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libbrcm_ril.so:system/lib/libbrcm_ril.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libbrcmcutils.so:system/lib/libbrcmcutils.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libbrcmparser.so:system/lib/libbrcmparser.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libbufmgmt.so:system/lib/libbufmgmt.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libbufpool.so:system/lib/libbufpool.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libcapi2.so:system/lib/libcapi2.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libcate_rpc.so:system/lib/libcate_rpc.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libcontainers.so:system/lib/libcontainers.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libdebug_sym.so:system/lib/libdebug_sym.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libdispmanx.so:system/lib/libdispmanx.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libhdcp.so:system/lib/libhdcp.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libHDCPKeyManager.so:system/lib/libHDCPKeyManager.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libhdmiaudio.so:system/lib/libhdmiaudio.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libjni_unbundled_latinimegoogle.so:system/lib/libjni_unbundled_latinimegoogle.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libmmal.so:system/lib/libmmal.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libmmal_components.so:system/lib/libmmal_components.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libmmal_util.so:system/lib/libmmal_util.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libmmal_vc.so:system/lib/libmmal_vc.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libomxmmal.so:system/lib/libomxmmal.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/librpc.so:system/lib/librpc.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libseckeyprov.so:system/lib/libseckeyprov.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsmct.so:system/lib/libsmct.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsoc.so:system/lib/libsoc.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libSoundAlive_VSP_ver312a.so:system/lib/libSoundAlive_VSP_ver312a.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libsthmb.so:system/lib/libsthmb.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libtvservice.so:system/lib/libtvservice.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libtvservice_binder.so:system/lib/libtvservice_binder.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libuecodec.so:system/lib/libuecodec.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libusb_config.so:system/lib/libusb_config.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libvcfiled.so:system/lib/libvcfiled.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libvchiq.so:system/lib/libvchiq.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libvchwtest_driver.so:system/lib/libvchwtest_driver.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libvcos.so:system/lib/libvcos.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libVCOS.so:system/lib/libVCOS.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libvcsm.so:system/lib/libvcsm.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/libWFC.so:system/lib/libWFC.so \
    vendor/samsung/galaxys2plus-common/proprietary/lib/modules/VoiceSolution.ko:system/lib/modules/VoiceSolution.ko \
    vendor/samsung/galaxys2plus-common/proprietary/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so:system/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so \
    vendor/samsung/galaxys2plus-common/proprietary/usr/lib/alsa-lib/libbcm_hp_filter.so:system/usr/lib/alsa-lib/libbcm_hp_filter.so \
    vendor/samsung/galaxys2plus-common/proprietary/usr/lib/alsa-lib/libbcm_test_filter.so:system/usr/lib/alsa-lib/libbcm_test_filter.so \
    vendor/samsung/galaxys2plus-common/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/egl/libGLES_vc4.so:system/vendor/lib/egl/libGLES_vc4.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/hw/camera.capri.so:system/vendor/lib/hw/camera.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/hw/gralloc.capri.so:system/vendor/lib/hw/gralloc.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/hw/hwcomposer.capri.so:system/vendor/lib/hw/hwcomposer.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/hw/lights.capri.so:system/vendor/lib/hw/lights.capri.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/libdrmmtkutil.so:system/vendor/lib/libdrmmtkutil.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/galaxys2plus-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
